# Generated by Django 3.1.3 on 2020-11-07 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_harvest_tree_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='gross_weight',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Gross weight'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='info',
            field=models.TextField(verbose_name='Informations'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='tree_group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='api.treegroup'),
        ),
        migrations.AlterField(
            model_name='specie',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='age',
            field=models.IntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='treegroup',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='treegroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
