# Generated by Django 3.1.3 on 2020-11-07 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201107_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='tree_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.treegroup'),
        ),
    ]
