# Generated by Django 3.1.3 on 2020-11-07 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201107_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvest',
            name='tree_group',
        ),
        migrations.AlterField(
            model_name='harvest',
            name='tree',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.tree'),
        ),
    ]
