# Generated by Django 3.1.3 on 2020-11-07 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201107_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='tree_group',
            field=models.OneToOneField(choices=[('Fruteiras', 'Fruteiras')], default='', on_delete=django.db.models.deletion.DO_NOTHING, to='api.treegroup'),
        ),
    ]
