# Generated by Django 3.1.3 on 2020-11-07 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_harvest_tree_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='tree_group',
            field=models.ForeignKey(choices=[('Fruteiras', 'Fruteiras')], default='', on_delete=django.db.models.deletion.DO_NOTHING, to='api.treegroup'),
        ),
    ]
