# Generated by Django 3.1.3 on 2020-11-07 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201107_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvest',
            name='tree_group',
        ),
    ]
